### ISSUE TITLE
Paquete retirado de cran 

### ISSUE THREAD

**Issue by verajosemanuel** [fmgarciadiaz/PortalHacienda-CRAN#1]
Hola!
Intente instalarlo de CRAN pero no está disponible. Gracias

Aprovecho para informarte de la existencia de un grupo que recopila paquetes para datos españoles con R. Podría ser interesante tu inclusión

https://ropenspain.es/paquetes/

**Comment by fmgarciadiaz** [comment]
Muchas gracias!! Sí, creo que cambió un link en la página del portal de datos y empezó a tirar errores la viñeta. Lo tengo que arreglar =/ Gracias por el aviso!!!!!

**Comment by fmgarciadiaz** [comment]
Corregí el manejo del timeout de la API y fue aceptado nuevamente en CRAN.
Ya deberías poder instalarlo nuevamente!

**Comment by verajosemanuel** [comment]
Muchisimas gracias, es un paquete muy util!

**Comment by fmgarciadiaz** [comment]
Gracias a vos por el aviso!! Que andes bien! =)
